<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.559"/>
    <xacro:property name="chassis_width" value="0.311"/>
    <xacro:property name="chassis_height" value="0.2795"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="front_wheel_radius" value="0.0375"/>
    <xacro:property name="rear_wheel_radius" value="0.040"/>
    <xacro:property name="front_wheel_thickness" value="0.029"/>
    <xacro:property name="rear_wheel_thickness" value="0.061"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="front_wheel_offset_y" value="0.0819"/>
    <xacro:property name="rear_wheel_offset_y" value="0.1101"/>
    

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-1 0 0.0415"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    
    <!-- FRONT LEFT AXEL LINK-->

    <joint name="front_left_axel_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_left_axel"/>
        <origin xyz="-0.5375 ${front_wheel_offset_y - 0.0319} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 -1 0"/>
        <limit lower="${-pi/4}" upper="${pi/4}" velocity="100" effort="100"/>
    </joint>

    <link name="front_left_axel">
        <visual>
            <geometry>
                <cylinder radius="0.005" length="0.0319"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.005"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.005" length="0.0319" radius="0.005">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="front_left_axel">
        <material>Gazebo/Red</material>
    </gazebo>

    <!-- FRONT LEFT WHEEL LINK -->

    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="front_left_axel"/>
        <child link="front_left_wheel"/>
        <origin xyz="0 0 0.0319" rpy="0 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="front_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${front_wheel_radius}" length="${front_wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${front_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${front_wheel_thickness}" radius="${front_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="front_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


  <!-- FRONT RIGHT AXEL LINK-->

    <joint name="front_right_axel_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_right_axel"/>
        <origin xyz="-0.5375 ${-front_wheel_offset_y + 0.0319} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 1 0"/>
        <limit lower="${-pi/4}" upper="${pi/4}" velocity="100" effort="100"/>
    </joint>

    <link name="front_right_axel">
        <visual>
            <geometry>
                <cylinder radius="0.005" length="0.0319"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.005"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.005" length="0.0319" radius="0.005">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="front_right_axel">
        <material>Gazebo/Red</material>
    </gazebo>

    <!-- FRONT RIGHT WHEEL LINK -->

    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="front_right_axel"/>
        <child link="front_right_wheel"/>
        <origin xyz="0 0 -0.0319" rpy="0 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="front_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${front_wheel_radius}" length="${front_wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${front_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${front_wheel_thickness}" radius="${front_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="front_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- REAR AXEL LINK -->

    <joint name="rear_axel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_axel"/>
        <origin xyz="-0.945 0 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="rear_axel">
        <visual>
            <geometry>
                <cylinder radius="0.005" length="0.2202"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${rear_wheel_radius}" length="0.2202"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="0.2202" radius="0.005">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="rear_axel">
        <material>Gazebo/Red</material>
    </gazebo>


    <!-- REAR LEFT WHEEL LINK -->

    <joint name="rear_left_wheel_joint" type="fixed">
        <parent link="rear_axel"/>
        <child link="rear_left_wheel"/>
        <origin xyz="0 0 ${rear_wheel_offset_y}" rpy="0 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="rear_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${rear_wheel_radius}" length="${rear_wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${rear_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${rear_wheel_thickness}" radius="${rear_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="rear_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


<!-- REAR RIGHT WHEEL LINK -->

    <joint name="rear_right_wheel_joint" type="fixed">
        <parent link="rear_axel"/>
        <child link="rear_right_wheel"/>
        <origin xyz="0 0 ${-rear_wheel_offset_y}" rpy="0 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="rear_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${rear_wheel_radius}" length="${rear_wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${rear_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${rear_wheel_thickness}" radius="${rear_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="rear_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

</robot>